### ISSUE TITLE
Feature request: Add links to source and license

### ISSUE THREAD

**Issue by gromenauer** [son-link/bestodon#3]
I ask for adding links to the source of the project (the main repo) and it's license.

I see in [bestodon](https://son-link.github.io/bestodon) main page:

> Welcome to this list of Mastodon accounts.  
> Here you can find accounts dedicated to **Free and Open Source** Software, such as games, applications, Linux distributions, etc. 

[rpginabox](https://mastodon.social/@rpginabox) is in the list, but don't seems to be open source (Is it?). I can't find it's repo. Having links to the source of the project and it's license in the bestodon entry dispels any doubts.

**Comment by son-link** [comment]
Oops, I thought it was, my mistake.
As for licenses, url to repositories, etc., it is a possibility, I am thinking about an improvement for the listings from which data is then extracted, where you can put several extra data, and it is something I have pending
